version: '3'
services:
  # redis:
  #   image: 'redis:alpine'
  #   volumes:
  #     - 'redis_data:./redis/data'
  #   ports:
  #     - '6379:6379'
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: news_recommend
      POSTGRES_USER: news_recommender
      POSTGRES_PASSWORD: nekopara
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/create-1.sql:/docker-entrypoint-initdb.d/init.sql