version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: news_recommend
      POSTGRES_USER: news_recommender
      POSTGRES_PASSWORD: nekopara
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/create-1.sql:/docker-entrypoint-initdb.d/init.sql