# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\rnewsrecommend\"I\n\x19GetRecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1b\n\x13num_recommendations\x18\x02 \x01(\x05\".\n\x1aGetRecommendationsResponse\x12\x10\n\x08news_ids\x18\x01 \x03(\t\"M\n\x0fUserInteraction\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07news_id\x18\x02 \x01(\t\x12\x18\n\x10interaction_type\x18\x03 \x01(\t\"-\n\x1a\x41\x64\x64UserInteractionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xdf\x01\n\rNewsRecommend\x12k\n\x12GetRecommendations\x12(.newsrecommend.GetRecommendationsRequest\x1a).newsrecommend.GetRecommendationsResponse\"\x00\x12\x61\n\x12\x41\x64\x64UserInteraction\x12\x1e.newsrecommend.UserInteraction\x1a).newsrecommend.AddUserInteractionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_start=29
  _globals['_GETRECOMMENDATIONSREQUEST']._serialized_end=102
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_start=104
  _globals['_GETRECOMMENDATIONSRESPONSE']._serialized_end=150
  _globals['_USERINTERACTION']._serialized_start=152
  _globals['_USERINTERACTION']._serialized_end=229
  _globals['_ADDUSERINTERACTIONRESPONSE']._serialized_start=231
  _globals['_ADDUSERINTERACTIONRESPONSE']._serialized_end=276
  _globals['_NEWSRECOMMEND']._serialized_start=279
  _globals['_NEWSRECOMMEND']._serialized_end=502
# @@protoc_insertion_point(module_scope)
