# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import data_pb2 as data__pb2


class NewsRecommendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/newsrecommend.NewsRecommend/GetRecommendations',
                request_serializer=data__pb2.GetRecommendationsRequest.SerializeToString,
                response_deserializer=data__pb2.GetRecommendationsResponse.FromString,
                )
        self.AddUserInteraction = channel.unary_unary(
                '/newsrecommend.NewsRecommend/AddUserInteraction',
                request_serializer=data__pb2.UserInteraction.SerializeToString,
                response_deserializer=data__pb2.AddUserInteractionResponse.FromString,
                )


class NewsRecommendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserInteraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NewsRecommendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=data__pb2.GetRecommendationsRequest.FromString,
                    response_serializer=data__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'AddUserInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserInteraction,
                    request_deserializer=data__pb2.UserInteraction.FromString,
                    response_serializer=data__pb2.AddUserInteractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'newsrecommend.NewsRecommend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NewsRecommend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/newsrecommend.NewsRecommend/GetRecommendations',
            data__pb2.GetRecommendationsRequest.SerializeToString,
            data__pb2.GetRecommendationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/newsrecommend.NewsRecommend/AddUserInteraction',
            data__pb2.UserInteraction.SerializeToString,
            data__pb2.AddUserInteractionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
